# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:1337/shiftAssignment
Cookie: io=-1Wf1aMxoUYujq1MAAAB; sails.sid=s%3AwSPo-V31GdK2xEzlNED7eWQ6dse4llvL.Vep8pM%2FmELP8IRHgIFzBqZBsxPQjfFU6%2FCaLyMkKNLY



###
DELETE http://localhost:1337/shiftAssignment/5b9c6f67fca126056f8b95a4
Cookie: io=-1Wf1aMxoUYujq1MAAAB; sails.sid=s%3AwSPo-V31GdK2xEzlNED7eWQ6dse4llvL.Vep8pM%2FmELP8IRHgIFzBqZBsxPQjfFU6%2FCaLyMkKNLY

###
